### ISSUE TITLE
Misleading saveObj behaviour

### ISSUE THREAD

**Issue by mathieuboudreau** [qMRLab/qMRLab#200] opened 2018-04-23 14:19 UTC
When calling the saveObj method, the argument of the method is the filename that we want to save the object as (as most other save methods in any program). However, the method overrides this, takes the prefix, and renames the filename to (prefix).qmrlab.mat, which is an unexpected behaviour on the users side.

https://github.com/neuropoly/qMRLab/blob/cafdf0185361b7331e64400fb707df76bb715015/Common/AbstractModel.m#L22-L38

Not sure why it was necessary to add the second suffix (?) `.qmrlab.`? 

I found this bug (feature?) while running my MATLAB test suite (https://github.com/neuropoly/qMRLab/blob/cafdf0185361b7331e64400fb707df76bb715015/Test/runTestSuite.m -> https://github.com/neuropoly/qMRLab/blob/cafdf0185361b7331e64400fb707df76bb715015/Test/Models/AbstractModel_Test.m), which tries to save the AbstractModel to a the file `tmp.mat`, and it errors because when it tries to load the expected file (`tmp.mat`), it is not there.

**Comment by agahkarakuzu** [comment] 2018-04-23 14:47
@mathieuboudreau `.qmrlab.` suffix was intended to serve as an identifier that distinguishes the record of a fit session by relating it to its model, while keeping it isolated from the other mat files in a directory, with Octave compatibility in mind. Object loading was more problematic there. 

As for `tmp.mat` issue I am not quite sure what that script does. I will look into that, we can discuss more today's meeting.

**Comment by tanguyduval** [comment] 2018-05-17 08:55
I propose to raise an error if the user includes an extension different than `.qmrlab.mat`. And add the extension if missing.
`.qmrlab.mat`is a way to identify which file can be loaded with qMRLoad

**Comment by tanguyduval** [comment] 2018-05-19 10:27
> * There is confusions with what *.qmrlab.* is intended to contain/enforce.
>     * It is enforced for qMRLab models when saving, which I can understand
>     * It is also enforced when saving fitting options, as can be seen in my issue #217 
qMRLab models properties contain both fitting options + protocol. So, when saving a model, you save both the fitting options and the protocol. On the GUI, when you click save, you save the entire model.
>     * It is enforced as an identifier that distinguishes the record of a fit session by relating it to its model, as mentionned by @agahkarakuzu 
After the fitting is complete, the idea was to save the entire model again, so that other group can reproduce the study easily. Currently the model is hidden inside the Fitresults.mat file, I agree we should separate those 2 files.

> So if I as a user has subject01.qmrlab.mat.... is this a model, fitting output, or the fitting options used for that session? As you can see, this added text does not necessarily guarantee or translate into added useful information (at least, not to me it doesn't). If the user isn't careful and depends on this "feature" too much as a sole identifier, they may overwrite a saved model with saved fitting output.
it should always be the entire model

> 
> What I would propose is this:
> 
> * When saving qMRLab models (which are classes converted to structs), **enforce a .qmr file extension.**
>     * (Mat)Lab's file extensions are *.mat, **so it only makes logical sense that (qMR)Lab's proprietary file extension would be .qmr**
ok for .qmr (.mat was a way to help dev to know the format, but I understand your point).
I guess we should also change the saving format to .json (more universal)

>     * Since they contain a qMRLab class, we want to enforce this with a non-mat file extension, as messing around with it at a *.mat file outside of the qMRLab environment can break it from loading.
> * When saving fitted data:
>     * simply use *.mat, because users are free to reuse these outputs in any other software pipelines, the fitted data is not only meant to be used in qMRLab but in any MATLAB environment session.
I propose to save images as `.nii.gz` and the results model as `.qmr` 
>         * It should be up to the user to save it and organize it accordingly.
>     * If we do use automated filename generations for pipelines, then using a (prefix)_qmr.mat pattern.
> * When saving fitting options:
>     * simply use *.mat as an option, because users are free to reuse these outputs in any other software pipelines.
>         * It should be up to the user to save it and organize it accordingly.
>     * this also doesn't need a _qmr/.qmrlab enforcement, because I feel like these fitting options may be shareable in the future in other formats. E.g., VFA fitting options saved in JSON format in qMRLab should be compatible with running it in [QUIT](https://github.com/spinicist/QUIT)
Here we should save save the entire model (all properties) as a .qmr file. It will be much cleaner in the code (we just use the method qmrLoadObj)... As I proposed above, the .qmr file should be a json file, which could be turn into a QUIT compatible file quite easily if the user wants.

>     * We also expect that the user can load the fitting options in Matlab and modify them manually there in that environment (I've done this in my project [qmt-optimization](https://github.com/mathieuboudreau/qmt-optimization))
Models (that contain fitting options) can be modified after loading. It should not be a problem

**Comment by mathieuboudreau** [comment] 2018-05-19 13:30
> qMRLab models properties contain both fitting options + protocol. So, when saving a model, you save both the fitting options and the protocol. On the GUI, when you click save, you save the entire model.

I see, I just noticed that you are correct, when saving you save the entire class object. I thought that "useless" non-fitting parameters like `buttons` weren't being saved with the fitting options, but I just checked and they are. I personally think they shouldn't, but since there are so few right now, I don't currently see it as an issue to remove them and give separation. Thanks for clarifying!

> After the fitting is complete, the idea was to save the entire model again, so that this file can be shared easily with other group (in order to help reproducibility). Currently the model is hidden inside the Fitresults.mat file, I agree we should separate those 2 files.

Ok! I do see your point as to why have them contained together, but would also like that option only save the images. Hmm, not sure how to support both options without cluttering the GUI with another button 😅.

> I guess we should also change the saving format to .json (more universal)
> Here we should save save the entire model (all properties) as a .qmr file. It will be much cleaner in the code (we just use the method qmrLoadObj)... As I proposed above, the .qmr file should be a json file, which could be turn into a QUIT compatible file quite easily if the user wants.

It's really easy provide the option to save as both formats (*.qmr ("mat") or JSON), and I think we should. As it is today, the *.qmr model file is a class converted to a struct, and structs are easily converted to JSON format using JSONlab which is already on the repo (JSON was basically designed to contain structs). We could default it to *.qmr ("mat") so that advanced users (see last point below) can load them in Matlab to do modifications, but just give a drop-down option for *.json so that it may be used in other projects (e.g. QUIT)

> I propose to save results as .nii.gz (compatible with other softwares) and the model as .qmr

Since we also support loading data as *.mat file, I feel like we should allow saving fitting results as *.mat files as well. There is a wide range of users who don't use .nii.gz (e.g. me during my entire PhD – I used MINC). For those users, it's great to allow at least the option to 1- load the data from whatever format they want into mat, and then 2- save the data in .mat, so they can convert it into their format themselves. This implicitly makes qMRLab support any file format without the messiness of implementing each of them, by letting the user loads it/save it into .mat themselves. But I'm fine (actually, really want) with *giving an option* to save the fitted data as .nii.gz, which we currently don't do.

>When saving fitting options:
simply use *.mat as an option, because users are free to reuse these outputs in any other software pipelines.
It should be up to the user to save it and organize it accordingly.
this also doesn't need a _qmr/.qmrlab enforcement, because I feel like these fitting options may be shareable in the future in other formats. E.g., VFA fitting options saved in JSON format in qMRLab should be compatible with running it in QUIT

>>Here we should save save the entire model (all properties) as a .qmr file. It will be much cleaner in the code (we just use the method qmrLoadObj)... 

Ok, I agree now.

> It will be much cleaner in the code (we just use the method qmrLoadObj)... 

Ok, I agree now.

> Models (that contain fitting options) can be modified after loading. It should not be a problem

My point was that saved models are class objects converted to structs which needs to have the exact same parameter names. We (devs on the project) know this and would know how to do this correctly, but there is a large class of users users that won't and could "break" their saved model files if they accidentally rename a parameter or don't properly change it. I think having the *.qmr "wall" (which might not be auto-loaded by Matlab when double clicked) might protect that class of unexperienced users from themselves. For other more advanced users - we could add a File Format section in the documentation that explains what is contained in this file (e.g. it's just a .mat file, but contains all class properties, so change at your own risk).

**Comment by tanguyduval** [comment] 2018-05-19 17:31
Agreed. BTW, we should remove all props `buttons` from the saved object...

> We could default it to *.qmr ("mat") so that advanced users (see last point below) can load them in Matlab to do modifications

I'm not a big fan of having 2 formats (mat and json) for *.qmr. If dev have methods to load json files in Matlab (e.g. using JSONlab) it should ok no? I don't see your point I guess

**Comment by mathieuboudreau** [comment] 2018-05-19 17:33
Sorry, I didn't mean that the data within the *.qmr is formatted in two different ways. I meant that we could save the fitting options in two different formats (e.g. like you can save a word file as a *.docx or a *.pdf, not that the *.docx file is formatted in two different ways (Microsoft and PDF)).

**Comment by tanguyduval** [comment] 2018-10-18 10:19
close this issue?

**Comment by agahkarakuzu** [comment] 2019-01-04 01:44
Merged #218.

**Closed by agahkarakuzu** 2019-01-04 01:44 UTC
Labels: discussion needed
