### ISSUE TITLE
GUI and CLI are giving different results

### ISSUE THREAD

**Issue by Danirid** [qMRLab/qMRLab#438] opened 2021-03-28 00:10 UTC
**Quick summary**
I have been using qMRLab for the past 4 months especially the qsm_sb Model. Recently, I've been interested in the batch code, so I tried to reconstruct my data using this code, but the results were different from GUI.

**Expected Behavior:**
I expected that the GUI and the batch code will give the same results.

**Current Behavior:**
The  Reconstruction of QSM image using the batch gave different results from using the GUI. The image using batch was blurry and worse comparing to the GUI

 **Detailed Description:**
First of all, I reconstruct QSM data using GUI, then I used the batch code after modifying it a little bit (I wrote the options panel code manually and assign each data to its parameters : Resolution, Timing...). The image resulting from the batch was different from the GUI.

**Sample code:**
qMRinfo('qsm_sb'); 
Model = qsm_sb; 

Model.options.DerivativeDirection='forward';
Model.options.SharpFiltering=true;
Model.options.SharpMode='once';
Model.options.PaddingSize= [9 9 9];
Model.options.MagnitudeWeighting=true;
Model.options.RegularizationSelection_SplitBregman=true;
Model.options.RegularizationSelection_L1Regularized=true;
Model.options.RegularizationSelection_L2Regularized=true;
Model.options.RegularizationSelection_NoRegularization=false;
Model.options.L1Panel_LambdaL1=9.21055e-04;
Model.options.L1Panel_ReOptimizeLambdaL1=false;
Model.options.L1Panel_L1Range=[-4 -2.5000 15];
Model.options.L2Panel_LambdaL2=0.0316228;
Model.options.L2Panel_ReOptimizeLambdaL2=false;
Model.options.L2Panel_L2Range=[-3 0 15];

data = struct();
 FileP=load_untouch_nii('Phase_File_Name.nii.gz');
 FileM=load_untouch_nii('Magnitude_File_Name.nii.gz');
 FileMa=load_untouch_nii('Mask_File_Name.nii.gz');
 
 Model.Prot = struct('Resolution',struct('Format',{{'xDim (mm)' 'yDim (mm)' 'zDim (mm)'}},...
'Mat', [0.3906 0.3906 1.6] ),...
'Timing',struct('Format',{{'TE (s)'}},...
'Mat', [12; 15.008; 18.016]), ...
'Magnetization', struct('Format', {{'FieldStrength (T)' 'CentralFreq (MHz)'}}, 'Mat', [3 42.58]));

data.PhaseGRE= double(FileP.img);
data.MagnGRE= double(FileM.img);
data.Mask= double(FileMa.img);
FitResults = FitData(data,Model,0);
qMRshowOutput(FitResults,data,Model);
FitResultsSave2=nii(FitResults);
Model.saveObj('qsm_sb_Demo.qmrlab.mat');

**Comment by tanguyduval** [comment] 2021-03-28 09:41
Hi danirid,

I suspect the use of `load_nii_untouch` to be the cause of the dissimilarity.

Can you try with `load_nii_data` instead. That forces the orientation of the image to be LPI.

Best
Tanguy

**Comment by Danirid** [comment] 2021-03-28 15:17
@tanguyduval it worked thank you so much

Daniel

**Comment by agahkarakuzu** [comment] 2021-03-28 16:15
Thank you @tanguyduval! 

@Danirid please feel free to close this issue if you don't have other questions. Thank you for reaching out 🙂

**Closed** 2021-03-28 16:18 UTC
