### ISSUE TITLE
UX feedback on new GUI image viewer features

### ISSUE THREAD

**Issue by mathieuboudreau** [qMRLab/qMRLab#327] opened 2019-04-03 22:00 UTC
First off, the new GUI image viewer is amazing. 🎉🎉🎉👏❤️

This issue is more of a discussion, maybe some changes will come out of it.

I wasn't a reviewer on the recent PRs (#296 #322 #323), so I encountered a few issues when using it tonight for the first time, which lead me to go through my pull review guidelines checklist for the GUI (Item 8 here: https://github.com/qMRLab/qMRLab/wiki/Guideline:-Reviewing-a-pull-request)

Here are a few minor things that I noticed following that list (MacOS 10.14.3 & MATLAB 2018a).

* After downloading an example dataset (tried with inversion recovery and VFA), images load using the "view' button, but the mask (clicking "view" next to the mask) doesn't display as it did before. "View" only loads the original dataset image (e.g. for VFA, it loads VFAdata) with the mask overlay. **If we don't want to display the mask as a standalone image anymore, we should remove the "view" button next to masks.**
* I can't seem figure out how to zoom (using Macbook touchpad). Tried a bunch of combination (click & drag, pinch, two finger drag, etc). Is it impossible to do with a touchpad; if not, some aditionnal instruction to the user is warranted.
* Scale bar is now missing.

Thoughts?

**Comment by mathieuboudreau** [comment] 2019-04-03 22:09
Another thing I missed. My installation has the Image Processing Toolbox add-on, however I am getting the warning message that I don't have it:

<img width="1436" alt="Capture d’écran 2019-04-03 à 19 38 45" src="https://user-images.githubusercontent.com/1421029/55516580-35195f00-5648-11e9-8f52-81bc9336efed.png">

**Comment by tanguyduval** [comment] 2019-04-03 22:18
Thx for the feedbacks @mathieuboudreau !
To zoom with trackpad: shift + click and drag (that will replace middle click and drag).
It's documented on the readthedoc and directly on the interface after you click the question mark:
![image](https://user-images.githubusercontent.com/7785316/55516843-c4396d80-566e-11e9-9703-cb43bf9a326c.png)

I'll turn this button in blue to make it more visible and clarify in the help what are the trackpad commands.
I'll have a look at other issues next week

**Comment by mathieuboudreau** [comment] 2019-04-03 22:22
Ahh, I didn't check to click there. Maybe we could have a hover tooltip above the "zoom" button as well; I'm merging Agah's PR on those tooltips soon. @agahkarakuzu do you think it is possible to do?

**Comment by agahkarakuzu** [comment] 2019-04-04 15:07
@mathieuboudreau tooltip in that PR was specific to the tables that are created by the model-based GUI generation framework.

Adding tooltips to individual GUI elements is also possible, and should be more straightforward.

**Comment by agahkarakuzu** [comment] 2019-04-05 01:29
@mathieuboudreau can you please check if you can fit `vfa_t1` using GUI? I wonder if you are going to hit `FitData L-172`? Because I could not, and wonder if it reproduces. 

https://github.com/qMRLab/qMRLab/blob/28cd8caf88613da9b29ef5cd8afcde23813beae1/src/Common/FitData.m#L171-L173

Other than that, following warnings are displayed upon opening, and each time `imtool3D` is being evoked:

![image](https://user-images.githubusercontent.com/9632322/55598422-9ad91a00-5720-11e9-91e6-939c408c841a.png)

**Comment by mathieuboudreau** [comment] 2019-04-05 01:37
@agahkarakuzu I had no issues fitting the demo VFA data or hitting that line, using the branch in #330.

Steps I followed:

* Opened `qMRLab`
* Change model to `vfa_t1`
* Clicked `Download example`
* Clicked `Fit data`

I'm on MacOS 10.14.14 and MATLAB R2018a

**Comment by agahkarakuzu** [comment] 2019-04-05 01:40
Thanks @mathieuboudreau ! It is interesting that I did not run into an issue on my Ubuntu machine, but had this problem on OSX 10.14.3 with R2015b. 

I will take a deeper look into this after restarting (will try on R2018a as well), my computer is not feeling good right now, I will treat it better and see.

**Comment by mathieuboudreau** [comment] 2019-04-05 01:43
Try some ginger and honey tea

**Comment by agahkarakuzu** [comment] 2019-04-12 04:30
@mathieuboudreau AFAICS all the issues raised here has been resolved. If you agree so, please close this issue

I suggest keeping GUI enhancements idle (or silent) unless there is a need for a hotfix until the release. Many thanks @tanguyduval for the amazing work!

**Comment by agahkarakuzu** [comment] 2019-04-16 06:12
Thank you for the great work. Closing this issue, hope to see user requests/feedbacks on the forum :)

**Closed by agahkarakuzu** 2019-04-16 06:12 UTC
Labels: discussion needed
